dist: bionic
language: python
notifications:
  email:
    on_success: never
    # on_failure: always
python:
  # - "3.6"
  - "3.7"
  # - "3.8"
os:
  - linux
#  - osx
sudo: false
install:
  - pip install -r requirements.txt
script:
  - pytest